name: Build-Test

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: npm install, build, test
      run: |
        npm ci
        npm run build --if-present
        npm run test
